function [t1, t2, L, gof] = allignement_verification(tds, dec, MISC_struct, audio_struct, perm_stat, do_plot)
    

    tds = tds(tds<length(audio_struct.signal));
    F_h_x = cosine_filter(length(MISC_struct.signal),...
                         {'high' 'low'},...
                         [50 330]/MISC_struct.Fs*2,...
                         [5 5]/MISC_struct.Fs*2);
    MISCf = real(...
                ifft(...
                    fft(...
                        MISC_struct.signal).*F_h_x)...
                        );
    F_h_x = cosine_filter(length(audio_struct.signal),...
                          {'high' 'low'}, ...
                          [50 330] / audio_struct.Fs*2, ...
                          [5 5] / audio_struct.Fs*2);
    Yf = real(...
            ifft(...
                fft( ...
                    audio_struct.signal).*F_h_x)...
                    );
    Yds = Yf(tds);
    L = min(length(MISC_struct.signal) - max(dec, 0),...
            length(Yds) + max(-dec, 0));
    t1 = max(dec, 0)+(1:L);
    t2 = max(-dec, 0)+(1:L);

    if do_plot == true
        plot(MISCf(t1));    hold on
        plot(Yds(t2)/norm(Yds(t2)) * norm(MISCf(t1)), 'g');
    end

    if ~perm_stat
        gof = corr(abs(MISCf(t1))', abs(Yds(t2))');
        disp(['g.o.f of the sound coregistration = ', num2str(gof), '. Should be above 0.5'])
    end

end